# Generated by Django 5.2.14 on 2026-05-05 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_usuarios_acceso_suscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_bucket', models.CharField(max_length=120)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1000, unique=True)),
                ('public_url', models.URLField(blank=True, max_length=1200)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('file_type', models.CharField(default='general', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'uploaded_files',
                'indexes': [models.Index(fields=['owner', 'file_type'], name='uploaded_fi_owner_i_5fb967_idx'), models.Index(fields=['created_at'], name='uploaded_fi_created_f8998f_idx')],
            },
        ),
    ]
