# Generated by Django 5.2.14 on 2026-05-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=120)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField()),
            ],
            options={
                'db_table': 'audit_events',
                'indexes': [models.Index(fields=['event'], name='audit_event_event_def0cb_idx'), models.Index(fields=['at'], name='audit_event_at_5b6779_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_user_id', models.UUIDField(db_index=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=1000)),
                ('role', models.CharField(choices=[('CLIENTE', 'Cliente'), ('COCINERO', 'Cocinero'), ('ADMINISTRADOR', 'Administrador'), ('REPARTIDOR', 'Repartidor')], default='CLIENTE', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('accept_terms', models.BooleanField(default=False)),
                ('notify_gmail', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_mongo_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['role'], name='user_profil_role_fa03e1_idx'), models.Index(fields=['email'], name='user_profil_email_8a1024_idx')],
            },
        ),
    ]
