# Generated by Django 5.2.14 on 2026-05-08 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cocinero', '0001_initial'),
        ('gestion_usuarios_acceso_suscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MOCK', 'Mock'), ('STRIPE', 'Stripe'), ('CRYPTO', 'Cripto')], default='MOCK', max_length=20)),
                ('type', models.CharField(choices=[('MOCK', 'Mock'), ('CARD', 'Tarjeta'), ('WALLET', 'Wallet')], default='MOCK', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('public_identifier', models.CharField(blank=True, max_length=120)),
                ('wallet_public_address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_payment_methods', to='gestion_cocinero.chefprofile')),
            ],
            options={
                'db_table': 'ai_payment_methods',
            },
        ),
        migrations.CreateModel(
            name='AISubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BOB', max_length=3)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible'), ('DISABLED', 'Deshabilitado')], default='AVAILABLE', max_length=20)),
                ('ai_query_limit', models.PositiveIntegerField(default=0)),
                ('ai_generation_limit', models.PositiveIntegerField(default=0)),
                ('vision_enabled', models.BooleanField(default=False)),
                ('production_recommendations_enabled', models.BooleanField(default=False)),
                ('pricing_support_enabled', models.BooleanField(default=False)),
                ('publishing_support_enabled', models.BooleanField(default=False)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_subscription_plans',
                'indexes': [models.Index(fields=['status'], name='ai_subscrip_status_164bd5_idx'), models.Index(fields=['created_at'], name='ai_subscrip_created_75322e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChefAISubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('CANCELLED', 'Cancelada'), ('PENDING_PAYMENT', 'Pendiente de pago'), ('EXPIRED', 'Vencida'), ('SUSPENDED', 'Suspendida')], default='PENDING_PAYMENT', max_length=30)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('preferred_payment_provider', models.CharField(default='MOCK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_subscriptions', to='gestion_cocinero.chefprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='gestion_usuarios_acceso_suscripcion.aisubscriptionplan')),
            ],
            options={
                'db_table': 'chef_ai_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='AISubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('PENDING', 'Pendiente'), ('ERROR', 'Error')], max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('crypto_transaction_hash', models.CharField(blank=True, max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_subscription_payments', to='gestion_cocinero.chefprofile')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gestion_usuarios_acceso_suscripcion.aipaymentmethod')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='gestion_usuarios_acceso_suscripcion.aisubscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='gestion_usuarios_acceso_suscripcion.chefaisubscription')),
            ],
            options={
                'db_table': 'ai_subscription_payments',
            },
        ),
        migrations.CreateModel(
            name='AISubscriptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PLAN_VIEWED', 'Plan visto'), ('SUBSCRIPTION_STATUS_VIEWED', 'Estado visto'), ('SUBSCRIPTION_SUMMARY_GENERATED', 'Resumen generado'), ('SUBSCRIPTION_CREATED', 'Suscripcion creada'), ('SUBSCRIPTION_ACTIVATED', 'Suscripcion activada'), ('PLAN_CHANGED', 'Plan cambiado'), ('CANCELLATION_REQUESTED', 'Cancelacion solicitada'), ('CANCELLATION_CONFIRMED', 'Cancelacion confirmada'), ('RENEWAL_REQUESTED', 'Renovacion solicitada'), ('RENEWAL_FAILED', 'Renovacion fallida'), ('PAYMENT_APPROVED', 'Pago aprobado'), ('PAYMENT_REJECTED', 'Pago rechazado'), ('AI_ACCESS_VALIDATED', 'Acceso IA validado'), ('AI_ACCESS_DENIED', 'Acceso IA denegado')], max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_subscription_audit_logs', to='gestion_cocinero.chefprofile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='gestion_usuarios_acceso_suscripcion.chefaisubscription')),
            ],
            options={
                'db_table': 'ai_subscription_audit_logs',
            },
        ),
        migrations.AddIndex(
            model_name='aipaymentmethod',
            index=models.Index(fields=['chef_profile'], name='ai_payment__chef_pr_79e8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='aipaymentmethod',
            index=models.Index(fields=['provider'], name='ai_payment__provide_7f2770_idx'),
        ),
        migrations.AddIndex(
            model_name='aipaymentmethod',
            index=models.Index(fields=['created_at'], name='ai_payment__created_3dcc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='chefaisubscription',
            index=models.Index(fields=['chef_profile'], name='chef_ai_sub_chef_pr_5c892f_idx'),
        ),
        migrations.AddIndex(
            model_name='chefaisubscription',
            index=models.Index(fields=['status'], name='chef_ai_sub_status_7cba8c_idx'),
        ),
        migrations.AddIndex(
            model_name='chefaisubscription',
            index=models.Index(fields=['plan'], name='chef_ai_sub_plan_id_87c472_idx'),
        ),
        migrations.AddIndex(
            model_name='chefaisubscription',
            index=models.Index(fields=['preferred_payment_provider'], name='chef_ai_sub_preferr_011b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='chefaisubscription',
            index=models.Index(fields=['created_at'], name='chef_ai_sub_created_461d21_idx'),
        ),
        migrations.AddIndex(
            model_name='chefaisubscription',
            index=models.Index(fields=['end_date'], name='chef_ai_sub_end_dat_eab92c_idx'),
        ),
        migrations.AddConstraint(
            model_name='chefaisubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('chef_profile',), name='unique_active_ai_subscription_per_chef'),
        ),
        migrations.AddIndex(
            model_name='aisubscriptionpayment',
            index=models.Index(fields=['chef_profile'], name='ai_subscrip_chef_pr_68b641_idx'),
        ),
        migrations.AddIndex(
            model_name='aisubscriptionpayment',
            index=models.Index(fields=['status'], name='ai_subscrip_status_d46c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='aisubscriptionpayment',
            index=models.Index(fields=['plan'], name='ai_subscrip_plan_id_d2aac4_idx'),
        ),
        migrations.AddIndex(
            model_name='aisubscriptionpayment',
            index=models.Index(fields=['provider'], name='ai_subscrip_provide_1e117f_idx'),
        ),
        migrations.AddIndex(
            model_name='aisubscriptionpayment',
            index=models.Index(fields=['created_at'], name='ai_subscrip_created_09050a_idx'),
        ),
        migrations.AddIndex(
            model_name='aisubscriptionauditlog',
            index=models.Index(fields=['chef_profile'], name='ai_subscrip_chef_pr_ff2e09_idx'),
        ),
        migrations.AddIndex(
            model_name='aisubscriptionauditlog',
            index=models.Index(fields=['subscription'], name='ai_subscrip_subscri_fe59c7_idx'),
        ),
        migrations.AddIndex(
            model_name='aisubscriptionauditlog',
            index=models.Index(fields=['action'], name='ai_subscrip_action_57918b_idx'),
        ),
        migrations.AddIndex(
            model_name='aisubscriptionauditlog',
            index=models.Index(fields=['created_at'], name='ai_subscrip_created_d6f67d_idx'),
        ),
    ]
