# Generated by Django 5.2.14 on 2026-05-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios_acceso_suscripcion', '0002_aipaymentmethod_aisubscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipaymentmethod',
            name='provider',
            field=models.CharField(choices=[('STRIPE_SANDBOX', 'Stripe Sandbox'), ('COINGATE_SANDBOX', 'CoinGate Sandbox')], max_length=20),
        ),
        migrations.AlterField(
            model_name='aipaymentmethod',
            name='type',
            field=models.CharField(choices=[('MOCK', 'Mock'), ('CARD', 'Tarjeta'), ('WALLET', 'Wallet')], default='CARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='chefaisubscription',
            name='preferred_payment_provider',
            field=models.CharField(default='STRIPE_SANDBOX', max_length=20),
        ),
    ]
