# Generated by Codex on 2026-05-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_usuarios_acceso_suscripcion", "0003_alter_aipaymentmethod_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsoIA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("funcion", models.CharField(max_length=80)),
                ("fecha_intento", models.DateTimeField(auto_now_add=True)),
                ("permitido", models.BooleanField(default=False)),
                ("codigo_resultado", models.CharField(max_length=60)),
                ("mensaje_resultado", models.CharField(max_length=255)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos_ia",
                        to="gestion_usuarios_acceso_suscripcion.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "uso_ia",
                "indexes": [
                    models.Index(fields=["usuario"], name="uso_ia_usuario_d48868_idx"),
                    models.Index(fields=["funcion"], name="uso_ia_funcion_df79da_idx"),
                    models.Index(fields=["fecha_intento"], name="uso_ia_fecha_i_09ae30_idx"),
                    models.Index(fields=["permitido", "codigo_resultado"], name="uso_ia_permiti_0c5318_idx"),
                ],
            },
        ),
    ]
