# Generated by Django 5.2.6 on 2026-06-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios_acceso_suscripcion', '0005_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipaymentmethod',
            name='provider',
            field=models.CharField(choices=[('STRIPE_SANDBOX', 'Stripe'), ('COINGATE_SANDBOX', 'CoinGate')], max_length=20),
        ),
    ]
