# Generated by Django 5.2.14 on 2026-06-16 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios_acceso_suscripcion', '0007_deliveryprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAvailabilityHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_manual_status', models.CharField(blank=True, max_length=30)),
                ('next_manual_status', models.CharField(blank=True, max_length=30)),
                ('previous_effective_status', models.CharField(blank=True, max_length=30)),
                ('next_effective_status', models.CharField(blank=True, max_length=30)),
                ('active_assignments_count', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(choices=[('manual_available', 'Disponible manual'), ('manual_off_duty', 'Fuera de servicio manual'), ('auto_capacity_reached', 'Capacidad alcanzada'), ('auto_capacity_released', 'Capacidad liberada'), ('sync', 'Sincronizacion')], default='sync', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'delivery_availability_history',
            },
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='availability_effective_status',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('FUERA_DE_SERVICIO', 'Fuera de servicio')], default='FUERA_DE_SERVICIO', max_length=30),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='availability_manual_status',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('FUERA_DE_SERVICIO', 'Fuera de servicio')], default='FUERA_DE_SERVICIO', max_length=30),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='availability_status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='deliveryprofile',
            index=models.Index(fields=['availability_manual_status', 'availability_effective_status'], name='delivery_pr_availab_7fc34f_idx'),
        ),
        migrations.AddField(
            model_name='deliveryavailabilityhistory',
            name='delivery_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_history', to='gestion_usuarios_acceso_suscripcion.deliveryprofile'),
        ),
        migrations.AddIndex(
            model_name='deliveryavailabilityhistory',
            index=models.Index(fields=['delivery_profile', 'changed_at'], name='delivery_av_deliver_28af93_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryavailabilityhistory',
            index=models.Index(fields=['reason', 'changed_at'], name='delivery_av_reason_9badfb_idx'),
        ),
    ]
