# Generated by Django 5.2.14 on 2026-06-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios_acceso_suscripcion', '0008_deliveryavailabilityhistory_and_more'),
        ('gestion_usuarios_acceso_suscripcion', '0008_userprofile_fcm_token'),
    ]

    operations = [
    ]
