# Generated by Django 5.2.14 on 2026-05-05 21:12

import django.db.models.deletion
import modules.marketplace_platos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_usuarios_acceso_suscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_types', models.JSONField(blank=True, default=list)),
                ('diet_types', models.JSONField(blank=True, default=list)),
                ('price_range', models.JSONField(blank=True, default=dict)),
                ('legacy_mongo_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_preferences', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'marketplace_preferences',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceFavorite',
            fields=[
                ('id', models.CharField(default=modules.marketplace_platos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('favorite_type', models.CharField(max_length=20)),
                ('ref_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'marketplace_favorites',
                'indexes': [models.Index(fields=['favorite_type', 'ref_id'], name='marketplace_favorit_aa3e6a_idx')],
                'unique_together': {('user', 'favorite_type', 'ref_id')},
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReview',
            fields=[
                ('id', models.CharField(default=modules.marketplace_platos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('chef_ref_id', models.CharField(db_index=True, max_length=128)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('legacy_mongo_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reviews', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'marketplace_reviews',
                'indexes': [models.Index(fields=['chef_ref_id', 'is_public'], name='marketplace_chef_re_5a73b8_idx'), models.Index(fields=['rating'], name='marketplace_rating_2068a1_idx')],
            },
        ),
    ]
