# Generated by Django 5.2.14 on 2026-05-06 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cocinero', '0001_initial'),
        ('gestion_usuarios_acceso_suscripcion', '0001_initial'),
        ('marketplace_platos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacereview',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_reviews', to='gestion_cocinero.dish'),
        ),
        migrations.AddField(
            model_name='marketplacereview',
            name='dish_ref_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='marketplacereview',
            index=models.Index(fields=['dish_ref_id', 'is_public'], name='marketplace_dish_re_877d89_idx'),
        ),
    ]
