# Generated by Django 5.2.14 on 2026-05-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cocinero', '0003_chefavailability_deleted_at_chefavailability_version_and_more'),
        ('gestion_usuarios_acceso_suscripcion', '0004_usoia'),
        ('marketplace_platos', '0002_marketplacereview_dish_marketplacereview_dish_ref_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacefavorite',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacefavorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marketplacefavorite',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marketplacepreference',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacepreference',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marketplacereview',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marketplacereview',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='marketplacefavorite',
            index=models.Index(fields=['deleted_at'], name='marketplace_deleted_d4fc18_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacepreference',
            index=models.Index(fields=['deleted_at'], name='marketplace_deleted_c3702a_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacereview',
            index=models.Index(fields=['deleted_at'], name='marketplace_deleted_6cbe9c_idx'),
        ),
    ]
