# Generated by Django 5.2.14 on 2026-06-16 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios_acceso_suscripcion', '0008_userprofile_fcm_token'),
        ('marketplace_platos', '0003_marketplacefavorite_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacereview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_marketplace_reviews', to='gestion_usuarios_acceso_suscripcion.userprofile'),
        ),
    ]
