# Generated by Django 5.2.6 on 2026-06-13 13:10

import django.db.models.deletion
import modules.confianza_administracion_seguridad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_usuarios_acceso_suscripcion', '0006_alter_aipaymentmethod_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeviceToken',
            fields=[
                ('id', models.CharField(default=modules.confianza_administracion_seguridad.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20)),
                ('token', models.TextField(unique=True)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('device_label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_device_tokens', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'notification_device_tokens',
                'indexes': [models.Index(fields=['user', 'is_active', 'platform'], name='notificatio_user_id_9b5b17_idx'), models.Index(fields=['device_id', 'platform'], name='notificatio_device__baf23b_idx'), models.Index(fields=['last_seen_at'], name='notificatio_last_se_227abb_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperationalNotification',
            fields=[
                ('id', models.CharField(default=modules.confianza_administracion_seguridad.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('role_context', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(choices=[('ORDER', 'Pedido'), ('PAYMENT', 'Pago'), ('DELIVERY', 'Delivery'), ('INCIDENT', 'Incidencia')], max_length=20)),
                ('event_code', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=255)),
                ('order_ref', models.CharField(blank=True, max_length=64)),
                ('assignment_ref', models.CharField(blank=True, max_length=64)),
                ('incident_ref', models.CharField(blank=True, max_length=64)),
                ('action_label', models.CharField(blank=True, max_length=80)),
                ('action_web_path', models.CharField(blank=True, max_length=255)),
                ('action_mobile_route', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_notifications', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'operational_notifications',
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='operational_recipie_c9b278_idx'), models.Index(fields=['event_code', 'created_at'], name='operational_event_c_dba1f3_idx'), models.Index(fields=['order_ref', 'created_at'], name='operational_order_r_b48285_idx')],
            },
        ),
    ]
