# Generated by Django 5.2.14 on 2026-06-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confianza_administracion_seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalnotification',
            name='category',
            field=models.CharField(choices=[('ORDER', 'Pedido'), ('PAYMENT', 'Pago'), ('DELIVERY', 'Delivery'), ('INCIDENT', 'Incidencia'), ('INVENTORY', 'Inventario')], max_length=20),
        ),
    ]
