# Generated by Django 5.2.14 on 2026-06-17 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confianza_administracion_seguridad', '0002_alter_operationalnotification_category'),
        ('gestion_cocinero', '0005_merge_20260617_0156'),
        ('gestion_usuarios_acceso_suscripcion', '0009_merge_20260617_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('imagen_engañosa', 'Imagen engañosa'), ('descripcion_falsa', 'Descripción falsa'), ('contenido_inapropiado', 'Contenido inapropiado'), ('precio_falso', 'Precio falso'), ('informacion_incompleta', 'Información incompleta'), ('otro', 'Otro')], max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('descartado', 'Descartado')], default='pendiente', max_length=30)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gestion_cocinero.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'publication_reports',
            },
        ),
    ]
