# Generated by Django 5.2.14 on 2026-06-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confianza_administracion_seguridad', '0004_alter_operationalnotification_category'),
        ('confianza_administracion_seguridad', '0004_analisisvisualpublicacion'),
    ]

    operations = [
    ]
