# Generated by Django 5.2.6 on 2026-06-12 15:56

import django.db.models.deletion
import modules.pedidos_checkout_pagos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_cocinero', '0003_chefavailability_deleted_at_chefavailability_version_and_more'),
        ('gestion_usuarios_acceso_suscripcion', '0006_alter_aipaymentmethod_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.CharField(default=modules.pedidos_checkout_pagos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='BOB', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('CONVERTED', 'Convertido'), ('ABANDONED', 'Abandonado')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(limit_choices_to={'role': 'COCINERO'}, on_delete=django.db.models.deletion.PROTECT, related_name='client_carts_received', to='gestion_usuarios_acceso_suscripcion.userprofile')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='order_carts', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'order_carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=modules.pedidos_checkout_pagos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CART', 'Carrito'), ('CHECKOUT_PENDING', 'Checkout pendiente'), ('PENDING_PAYMENT', 'Pendiente de pago'), ('PAYMENT_VALIDATING', 'Validando pago'), ('PAYMENT_FAILED', 'Pago fallido'), ('PAID', 'Pagado'), ('AWAITING_CHEF_CONFIRMATION', 'Esperando confirmacion del cocinero'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado'), ('PREPARING', 'En preparacion'), ('READY_FOR_PICKUP', 'Listo para retiro'), ('READY_FOR_DELIVERY', 'Listo para entrega'), ('OUT_FOR_DELIVERY', 'En camino'), ('DELIVERED', 'Entregado'), ('PICKED_UP', 'Retirado'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado')], default='PENDING_PAYMENT', max_length=40)),
                ('fulfillment_type', models.CharField(choices=[('pickup', 'Retiro'), ('delivery', 'Delivery')], max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('bitcoin_coingate', 'Bitcoin CoinGate'), ('qr_simulado', 'QR simulado')], max_length=30)),
                ('currency', models.CharField(default='BOB', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('stock_reserved', models.BooleanField(default=False)),
                ('last_status_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by_role', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(limit_choices_to={'role': 'COCINERO'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_chef', to='gestion_usuarios_acceso_suscripcion.userprofile')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_client', to='gestion_usuarios_acceso_suscripcion.userprofile')),
                ('source_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_orders', to='pedidos_checkout_pagos.cart')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='converted_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_carts', to='pedidos_checkout_pagos.order'),
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.CharField(default=modules.pedidos_checkout_pagos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('line_1', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='pedidos_checkout_pagos.order')),
            ],
            options={
                'db_table': 'order_addresses',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(default=modules.pedidos_checkout_pagos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish_name_snapshot', models.CharField(max_length=160)),
                ('dish_description_snapshot', models.TextField(blank=True)),
                ('dish_image_url_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='gestion_cocinero.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos_checkout_pagos.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.CharField(default=modules.pedidos_checkout_pagos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('bitcoin_coingate', 'Bitcoin CoinGate'), ('qr_simulado', 'QR simulado')], max_length=30)),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('CONFIRMED', 'Confirmado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado')], default='CREATED', max_length=20)),
                ('currency', models.CharField(default='BOB', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('payment_url', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('qr_session_code', models.CharField(blank=True, db_index=True, max_length=120)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by_role', models.CharField(blank=True, max_length=30)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_order_payments', to='gestion_usuarios_acceso_suscripcion.userprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pedidos_checkout_pagos.order')),
            ],
            options={
                'db_table': 'order_payments',
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentEvent',
            fields=[
                ('id', models.CharField(default=modules.pedidos_checkout_pagos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('event_code', models.CharField(max_length=60)),
                ('event_label', models.CharField(max_length=160)),
                ('actor_role', models.CharField(max_length=30)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pedidos_checkout_pagos.orderpayment')),
            ],
            options={
                'db_table': 'order_payment_events',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.CharField(default=modules.pedidos_checkout_pagos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=40)),
                ('to_status', models.CharField(max_length=40)),
                ('actor_role', models.CharField(max_length=30)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pedidos_checkout_pagos.order')),
            ],
            options={
                'db_table': 'order_status_history',
            },
        ),
        migrations.CreateModel(
            name='OrderTimelineEvent',
            fields=[
                ('id', models.CharField(default=modules.pedidos_checkout_pagos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('event_code', models.CharField(max_length=60)),
                ('event_label', models.CharField(max_length=160)),
                ('actor_role', models.CharField(max_length=30)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='pedidos_checkout_pagos.order')),
            ],
            options={
                'db_table': 'order_timeline_events',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.CharField(default=modules.pedidos_checkout_pagos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dish_name_snapshot', models.CharField(max_length=160)),
                ('dish_image_url_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos_checkout_pagos.cart')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='gestion_cocinero.dish')),
            ],
            options={
                'db_table': 'order_cart_items',
                'indexes': [models.Index(fields=['cart', 'dish'], name='order_cart__cart_id_86d1b6_idx'), models.Index(fields=['updated_at'], name='order_cart__updated_d49ef7_idx')],
                'constraints': [models.UniqueConstraint(fields=('cart', 'dish'), name='unique_cart_item_per_dish')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='orders_client__2e756d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['chef', 'status'], name='orders_chef_id_612362_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fulfillment_type', 'status'], name='orders_fulfill_831ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'status'], name='orders_payment_88105c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['last_status_at'], name='orders_last_st_2a6bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['client', 'status'], name='order_carts_client__d340c9_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['chef', 'status'], name='order_carts_chef_id_9677cd_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['updated_at'], name='order_carts_updated_9cdab9_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('client', 'chef'), name='unique_active_cart_per_client_chef'),
        ),
        migrations.AddIndex(
            model_name='orderaddress',
            index=models.Index(fields=['latitude', 'longitude'], name='order_addre_latitud_23997a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'dish'], name='order_items_order_i_6682bc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['updated_at'], name='order_items_updated_8cff18_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['order', 'status'], name='order_payme_order_i_b14fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['method', 'status'], name='order_payme_method_91d032_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['provider', 'status'], name='order_payme_provide_aa9656_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['created_at'], name='order_payme_created_b9b989_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpaymentevent',
            index=models.Index(fields=['payment', 'occurred_at'], name='order_payme_payment_295f60_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpaymentevent',
            index=models.Index(fields=['event_code', 'occurred_at'], name='order_payme_event_c_597952_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'occurred_at'], name='order_statu_order_i_aaf4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['to_status', 'occurred_at'], name='order_statu_to_stat_8d1330_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimelineevent',
            index=models.Index(fields=['order', 'occurred_at'], name='order_timel_order_i_5c1c64_idx'),
        ),
        migrations.AddIndex(
            model_name='ordertimelineevent',
            index=models.Index(fields=['event_code', 'occurred_at'], name='order_timel_event_c_bb7c17_idx'),
        ),
    ]
