# Generated by Django 5.2.6 on 2026-06-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_checkout_pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_source_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_source_type',
            field=models.CharField(blank=True, choices=[('dish', 'Plato'), ('daily_menu_item', 'Menu del dia')], max_length=30),
        ),
    ]
