# Generated by Django 5.2.6 on 2026-06-12 20:11

import django.db.models.deletion
import modules.pedidos_checkout_pagos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_checkout_pagos', '0002_orderitem_stock_source_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedQRPaymentSession',
            fields=[
                ('id', models.CharField(default=modules.pedidos_checkout_pagos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('session_code', models.CharField(db_index=True, max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado'), ('INVALIDATED', 'Invalidado')], default='PENDING', max_length=20)),
                ('bank_name', models.CharField(default='Banco HomeChef', max_length=120)),
                ('bank_account_label', models.CharField(default='Cuenta QR simulada', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BOB', max_length=3)),
                ('expires_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='pedidos_checkout_pagos.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='pedidos_checkout_pagos.orderpayment')),
            ],
            options={
                'db_table': 'order_simulated_qr_sessions',
                'indexes': [models.Index(fields=['payment', 'status'], name='order_simul_payment_301482_idx'), models.Index(fields=['order', 'status'], name='order_simul_order_i_72db1c_idx'), models.Index(fields=['expires_at'], name='order_simul_expires_5ad4a5_idx'), models.Index(fields=['created_at'], name='order_simul_created_2b4e31_idx')],
            },
        ),
    ]
