# Generated by Django 5.2.6 on 2026-06-13 03:39

import django.db.models.deletion
import modules.pedidos_checkout_pagos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios_acceso_suscripcion', '0006_alter_aipaymentmethod_provider'),
        ('pedidos_checkout_pagos', '0003_simulatedqrpaymentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupConfirmation',
            fields=[
                ('id', models.CharField(default=modules.pedidos_checkout_pagos.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('pickup_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('pickup_instructions', models.CharField(default='Presenta este codigo al cocinero para retirar tu pedido.', max_length=255)),
                ('pickup_schedule_note', models.CharField(blank=True, max_length=255)),
                ('confirmed_by_role', models.CharField(blank=True, max_length=30)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_pickup_orders', to='gestion_usuarios_acceso_suscripcion.userprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_confirmation', to='pedidos_checkout_pagos.order')),
            ],
            options={
                'db_table': 'order_pickup_confirmations',
                'indexes': [models.Index(fields=['status', 'created_at'], name='order_picku_status_c72fc4_idx'), models.Index(fields=['confirmed_at'], name='order_picku_confirm_472918_idx')],
            },
        ),
    ]
