# Generated by Django 5.2.14 on 2026-06-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_checkout_pagos', '0007_orderreceipt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderreceipt',
            new_name='order_recei_order_i_d8c679_idx',
            old_name='order_recei_order_i_131937_idx',
        ),
        migrations.RenameIndex(
            model_name='orderreceipt',
            new_name='order_recei_payment_39ac6d_idx',
            old_name='order_recei_payment_e2f31a_idx',
        ),
        migrations.RenameIndex(
            model_name='pickupconfirmation',
            new_name='order_picku_pickup__f13c3c_idx',
            old_name='order_pickup_pickup__3ee4b3_idx',
        ),
    ]
