# Generated by Django 5.2.6 on 2026-06-13 02:28

import django.db.models.deletion
import modules.delivery_logistica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_usuarios_acceso_suscripcion', '0006_alter_aipaymentmethod_provider'),
        ('pedidos_checkout_pagos', '0003_simulatedqrpaymentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.CharField(default=modules.delivery_logistica.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Sin asignar'), ('ASSIGNED', 'Asignado'), ('EN_ROUTE_TO_CHEF', 'En ruta al cocinero'), ('AT_CHEF', 'En punto de recogida'), ('PICKED_UP', 'Recogido'), ('EN_ROUTE_TO_CLIENT', 'En ruta al cliente'), ('DELIVERED', 'Entregado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='UNASSIGNED', max_length=30)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'REPARTIDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments', to='gestion_usuarios_acceso_suscripcion.userprofile')),
                ('order', models.OneToOneField(limit_choices_to={'fulfillment_type': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='pedidos_checkout_pagos.order')),
            ],
            options={
                'db_table': 'delivery_assignments',
            },
        ),
        migrations.CreateModel(
            name='DeliveryIncident',
            fields=[
                ('id', models.CharField(default=modules.delivery_logistica.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('RESOLVED', 'Resuelta'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=20)),
                ('reported_by_role', models.CharField(max_length=30)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='delivery_logistica.deliveryassignment')),
                ('reported_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_delivery_incidents', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'delivery_incidents',
            },
        ),
        migrations.CreateModel(
            name='DeliveryLocationPing',
            fields=[
                ('id', models.CharField(default=modules.delivery_logistica.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('SYSTEM', 'Sistema'), ('DELIVERY_APP', 'App delivery')], default='SYSTEM', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('heading_degrees', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='delivery_logistica.deliveryassignment')),
            ],
            options={
                'db_table': 'delivery_location_pings',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.CharField(default=modules.delivery_logistica.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('actor_role', models.CharField(max_length=30)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery_logistica.deliveryassignment')),
            ],
            options={
                'db_table': 'delivery_status_history',
            },
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['status', 'created_at'], name='delivery_as_status_bd5483_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['delivery_user', 'status'], name='delivery_as_deliver_e75085_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['assigned_at'], name='delivery_as_assigne_c36169_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryincident',
            index=models.Index(fields=['assignment', 'status'], name='delivery_in_assignm_3a064e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryincident',
            index=models.Index(fields=['code', 'status'], name='delivery_in_code_1d3608_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryincident',
            index=models.Index(fields=['created_at'], name='delivery_in_created_d277e6_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylocationping',
            index=models.Index(fields=['assignment', 'recorded_at'], name='delivery_lo_assignm_be5a00_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylocationping',
            index=models.Index(fields=['latitude', 'longitude'], name='delivery_lo_latitud_51df2e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystatushistory',
            index=models.Index(fields=['assignment', 'occurred_at'], name='delivery_st_assignm_de7310_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverystatushistory',
            index=models.Index(fields=['to_status', 'occurred_at'], name='delivery_st_to_stat_859d75_idx'),
        ),
    ]
