# Generated by Django 5.2.6 on 2026-06-13 04:43

import django.db.models.deletion
import modules.delivery_logistica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRouteSnapshot',
            fields=[
                ('id', models.CharField(default=modules.delivery_logistica.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('route_kind', models.CharField(choices=[('TO_CHEF', 'Hacia cocinero'), ('TO_CLIENT', 'Hacia cliente')], max_length=20)),
                ('provider', models.CharField(default='OSM_FALLBACK', max_length=40)),
                ('is_current', models.BooleanField(default=True)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('distance_meters', models.FloatField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('polyline', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_snapshots', to='delivery_logistica.deliveryassignment')),
            ],
            options={
                'db_table': 'delivery_route_snapshots',
                'indexes': [models.Index(fields=['assignment', 'is_current'], name='delivery_ro_assignm_74073c_idx'), models.Index(fields=['route_kind', 'created_at'], name='delivery_ro_route_k_d049d7_idx')],
            },
        ),
    ]
