# Generated by Codex on 2026-06-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_usuarios_acceso_suscripcion", "0006_alter_aipaymentmethod_provider"),
        ("delivery_logistica", "0002_deliveryroutesnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryincident",
            name="code",
            field=models.CharField(
                choices=[
                    ("DELAY", "Retraso"),
                    ("WRONG_ADDRESS", "Direccion incorrecta"),
                    ("CLIENT_ABSENT", "Cliente ausente"),
                    ("ORDER_DAMAGED", "Pedido danado"),
                    ("CANCELLATION_REQUEST", "Solicitud de cancelacion"),
                    ("CANNOT_COMPLETE", "No se puede completar la entrega"),
                ],
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="deliveryincident",
            name="evidence_urls",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="deliveryincident",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="deliveryincident",
            name="resolved_by_role",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="deliveryincident",
            name="resolved_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_delivery_incidents",
                to="gestion_usuarios_acceso_suscripcion.userprofile",
            ),
        ),
    ]
