# Generated by Django 5.2.14 on 2026-06-16 05:26

import django.db.models.deletion
import modules.delivery_logistica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_logistica', '0003_deliveryincident_resolution_fields'),
        ('gestion_usuarios_acceso_suscripcion', '0008_deliveryavailabilityhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignmentOffer',
            fields=[
                ('id', models.CharField(default=modules.delivery_logistica.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('EXPIRED', 'Expirada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('offered_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_reason', models.CharField(blank=True, max_length=120)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('selection_distance_meters', models.FloatField(default=0)),
                ('selection_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='delivery_logistica.deliveryassignment')),
                ('delivery_user', models.ForeignKey(limit_choices_to={'role': 'REPARTIDOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment_offers', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'delivery_assignment_offers',
                'indexes': [models.Index(fields=['assignment', 'status'], name='delivery_as_assignm_c74883_idx'), models.Index(fields=['delivery_user', 'status'], name='delivery_as_deliver_9485b5_idx'), models.Index(fields=['expires_at'], name='delivery_as_expires_848522_idx'), models.Index(fields=['offered_at'], name='delivery_as_offered_e92798_idx')],
            },
        ),
    ]
