from django.urls import path
from .views import (
    admin_platform_users_collection_view,
    admin_platform_user_toggle_block_view,
    admin_platform_pending_chefs_view,
    admin_platform_chef_validate_view,
    admin_platform_publications_view,
    admin_platform_publication_action_view,
    delivery_active_order_detail_view,
    delivery_active_orders_collection_view,
    delivery_driver_status_update_view,
    delivery_drivers_collection_view,
    module_home,
    notification_devices_register_view,
    notification_devices_unregister_view,
    notifications_collection_view,
    notifications_mark_all_read_view,
    notifications_mark_read_view,
    list_publications,
    list_suspicious_publications,
    detail_publication,
    approve_publication,
    reject_publication,
    hide_publication,
    request_correction_publication,
    report_publication,
    list_approved_publications,
    list_correction_publications,
    list_hidden_publications,
    list_rejected_publications,
    delete_publication_permanent,
    visual_moderation_view,
)
from .views.dynamic_reports import DynamicReportsChatView, DynamicReportsExportView
from .views.audit import (
    AdminAuditAIDetailView,
    AdminAuditAIExportView,
    AdminAuditAISummaryView,
    AdminAuditAIView,
    AdminAuditGeneralDetailView,
    AdminAuditGeneralExportView,
    AdminAuditGeneralSummaryView,
    AdminAuditGeneralView,
)
from .views.sync import (
    AdminSyncBootstrapView,
    AdminSyncStatusView,
    AdminSyncPushView,
    AdminSyncModuleView,
)

urlpatterns = [
    path("sync/bootstrap", AdminSyncBootstrapView.as_view(), name="admin-sync-bootstrap"),
    path("sync/status", AdminSyncStatusView.as_view(), name="admin-sync-status"),
    path("sync/push", AdminSyncPushView.as_view(), name="admin-sync-push"),
    path("sync/module/<str:module_name>", AdminSyncModuleView.as_view(), name="admin-sync-module"),
    path("", module_home),
    path("delivery-orders/active/", delivery_active_orders_collection_view),
    path("delivery-orders/active/<str:order_id>/", delivery_active_order_detail_view),
    path("delivery-drivers/", delivery_drivers_collection_view),
    path("delivery-drivers/<str:user_id>/status/", delivery_driver_status_update_view),
    path("notifications/", notifications_collection_view),
    path("notifications/read-all/", notifications_mark_all_read_view),
    path("notifications/<str:notification_id>/read/", notifications_mark_read_view),
    path("notifications/devices/register/", notification_devices_register_view),
    path("notifications/devices/unregister/", notification_devices_unregister_view),
    path("users/", admin_platform_users_collection_view),
    path("users/<str:user_id>/toggle-block/", admin_platform_user_toggle_block_view),
    path("chefs/pending/", admin_platform_pending_chefs_view),
    path("chefs/<str:chef_id>/validate/", admin_platform_chef_validate_view),
    path("publications/", admin_platform_publications_view),
    path("publications/<str:dish_id>/action/", admin_platform_publication_action_view),
    path('publicaciones/calidad/', list_publications, name='admin-quality-list'),
    path('publicaciones/calidad/sospechosas/', list_suspicious_publications, name='admin-quality-suspicious'),
    path('publicaciones/calidad/aprobadas/', list_approved_publications, name='admin-quality-approved'),
    path('publicaciones/calidad/en-correccion/', list_correction_publications, name='admin-quality-in-correction'),
    path('publicaciones/calidad/ocultadas/', list_hidden_publications, name='admin-quality-hidden-list'),
    path('publicaciones/calidad/rechazadas/', list_rejected_publications, name='admin-quality-rejected-list'),
    path('publicaciones/calidad/<str:dish_id>/', detail_publication, name='admin-quality-detail'),
    path('publicaciones/calidad/<str:dish_id>/aprobar/', approve_publication, name='admin-quality-approve'),
    path('publicaciones/calidad/<str:dish_id>/rechazar/', reject_publication, name='admin-quality-reject'),
    path('publicaciones/calidad/<str:dish_id>/ocultar/', hide_publication, name='admin-quality-hide'),
    path('publicaciones/calidad/<str:dish_id>/solicitar-correccion/', request_correction_publication, name='admin-quality-request-correction'),
    path('publicaciones/calidad/<str:dish_id>/corregir/', request_correction_publication, name='admin-quality-correct'),
    path('publicaciones/calidad/<str:dish_id>/eliminar-definitivo/', delete_publication_permanent, name='admin-quality-delete-permanent'),
    path('publicaciones/calidad/<str:dish_id>/reportar/', report_publication, name='dish-report-alt'),
    path('publicaciones/calidad/<str:dish_id>/analizar-imagen-ia/', visual_moderation_view, name='admin-quality-visual-moderation'),
    path('dynamic-reports/chat/', DynamicReportsChatView.as_view(), name='dynamic-reports-chat'),
    path('dynamic-reports/export/', DynamicReportsExportView.as_view(), name='dynamic-reports-export'),
    path("audit/general/", AdminAuditGeneralView.as_view(), name="admin-audit-general"),
    path("audit/general/summary/", AdminAuditGeneralSummaryView.as_view(), name="admin-audit-general-summary"),
    path("audit/general/export/", AdminAuditGeneralExportView.as_view(), name="admin-audit-general-export"),
    path("audit/general/<int:audit_id>/", AdminAuditGeneralDetailView.as_view(), name="admin-audit-general-detail"),
    path("audit/ai/", AdminAuditAIView.as_view(), name="admin-audit-ai"),
    path("audit/ai/summary/", AdminAuditAISummaryView.as_view(), name="admin-audit-ai-summary"),
    path("audit/ai/export/", AdminAuditAIExportView.as_view(), name="admin-audit-ai-export"),
    path("audit/ai/<str:event_id>/", AdminAuditAIDetailView.as_view(), name="admin-audit-ai-detail"),
]
