from django.urls import path
from .views import (
    cart_items_collection_view,
    cart_items_item_view,
    cart_view,
    chef_order_accept_view,
    chef_order_detail_view,
    chef_order_incident_resolve_view,
    chef_order_incidents_view,
    chef_order_pickup_confirm_view,
    chef_order_preparing_view,
    chef_order_reject_view,
    chef_order_ready_view,
    chef_order_tracking_view,
    chef_orders_view,
    bitcoin_coingate_callback_view,
    bitcoin_coingate_confirm_return_view,
    checkout_confirm_view,
    checkout_preview_view,
    checkout_route_preview_view,
    client_order_cancel_view,
    delivery_cash_orders_view,
    delivery_order_cash_confirm_view,
    delivery_order_start_view,
    module_home,
    my_order_detail_view,
    my_order_incidents_view,
    my_order_tracking_view,
    my_orders_view,
    qr_session_cancel_view,
    qr_session_confirm_view,
    qr_session_detail_view,
    qr_session_start_view,
    stripe_confirm_return_view,
)

urlpatterns = [
    path("", module_home),
    path("cart/", cart_view),
    path("cart/items/", cart_items_collection_view),
    path("cart/items/<str:item_id>/", cart_items_item_view),
    path("checkout/preview/", checkout_preview_view),
    path("checkout/route-preview/", checkout_route_preview_view),
    path("checkout/confirm/", checkout_confirm_view),
    path("my-orders/", my_orders_view),
    path("my-orders/<str:order_id>/", my_order_detail_view),
    path("my-orders/<str:order_id>/tracking/", my_order_tracking_view),
    path("my-orders/<str:order_id>/incidents/", my_order_incidents_view),
    path("<str:order_id>/cancel/", client_order_cancel_view),
    path("chef/orders/", chef_orders_view),
    path("chef/orders/<str:order_id>/", chef_order_detail_view),
    path("chef/orders/<str:order_id>/tracking/", chef_order_tracking_view),
    path("chef/orders/<str:order_id>/incidents/", chef_order_incidents_view),
    path("chef/orders/<str:order_id>/incidents/<str:incident_id>/resolve/", chef_order_incident_resolve_view),
    path("chef/orders/<str:order_id>/accept/", chef_order_accept_view),
    path("chef/orders/<str:order_id>/reject/", chef_order_reject_view),
    path("chef/orders/<str:order_id>/preparing/", chef_order_preparing_view),
    path("chef/orders/<str:order_id>/ready/", chef_order_ready_view),
    path("chef/orders/<str:order_id>/pickup/confirm/", chef_order_pickup_confirm_view),
    path("delivery/cash-orders/", delivery_cash_orders_view),
    path("delivery/orders/<str:order_id>/start/", delivery_order_start_view),
    path("delivery/orders/<str:order_id>/confirm-cash/", delivery_order_cash_confirm_view),
    path("payments/bitcoin-coingate/confirm-return/", bitcoin_coingate_confirm_return_view),
    path("payments/stripe/confirm-return/", stripe_confirm_return_view),
    path("payments/bitcoin-coingate/callback/", bitcoin_coingate_callback_view),
    path("payments/qr-sessions/<str:session_code>/", qr_session_detail_view),
    path("payments/qr-sessions/<str:session_code>/start/", qr_session_start_view),
    path("payments/qr-sessions/<str:session_code>/confirm/", qr_session_confirm_view),
    path("payments/qr-sessions/<str:session_code>/cancel/", qr_session_cancel_view),
]
