# Generated by Django 5.2.14 on 2026-05-05 21:12

import django.db.models.deletion
import modules.gestion_cocinero.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_usuarios_acceso_suscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('weekly_schedule', models.JSONField(blank=True, default=list)),
                ('pickup_schedule', models.CharField(blank=True, max_length=255)),
                ('accept_delivery', models.BooleanField(default=True)),
                ('accept_pickup', models.BooleanField(default=True)),
                ('simultaneous_orders_limit', models.PositiveIntegerField(default=10)),
                ('legacy_mongo_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'chef_availability',
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('legacy_mongo_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menu', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'chef_daily_menu',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.CharField(default=modules.gestion_cocinero.models.uuid4_string, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portions', models.PositiveIntegerField(default=1)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('image_url', models.TextField(blank=True)),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('legacy_mongo_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'chef_dishes',
            },
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portions', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='available', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion_cocinero.dailymenu')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='gestion_cocinero.dish')),
            ],
            options={
                'db_table': 'chef_daily_menu_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChefProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=160)),
                ('public_description', models.TextField(blank=True)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('location_latitude', models.FloatField(blank=True, null=True)),
                ('location_longitude', models.FloatField(blank=True, null=True)),
                ('location_address', models.CharField(blank=True, max_length=255)),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('profile_image_url', models.TextField(blank=True)),
                ('status', models.CharField(default='pending_validation', max_length=40)),
                ('ai_subscription_active', models.BooleanField(default=False)),
                ('legacy_mongo_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_profile', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'chef_profiles',
                'indexes': [models.Index(fields=['status'], name='chef_profil_status_f2a79c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['chef', 'status'], name='chef_dishes_chef_id_eb941a_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['updated_at'], name='chef_dishes_updated_ae6654_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymenuitem',
            unique_together={('menu', 'dish')},
        ),
    ]
