# Generated by Django 5.2.14 on 2026-05-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cocinero', '0002_dish_offline_sync_fields'),
        ('gestion_usuarios_acceso_suscripcion', '0004_usoia'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefavailability',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chefavailability',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='chefavailability',
            index=models.Index(fields=['deleted_at'], name='chef_availa_deleted_7a3404_idx'),
        ),
        migrations.AddIndex(
            model_name='chefprofile',
            index=models.Index(fields=['deleted_at'], name='chef_profil_deleted_18f5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymenu',
            index=models.Index(fields=['deleted_at'], name='chef_daily__deleted_ab7a1e_idx'),
        ),
    ]
