# Generated by Django 5.2.14 on 2026-06-13 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cocinero', '0003_chefavailability_deleted_at_chefavailability_version_and_more'),
        ('gestion_usuarios_acceso_suscripcion', '0006_alter_aipaymentmethod_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('current_stock', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('low_stock_threshold', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='gestion_usuarios_acceso_suscripcion.userprofile')),
            ],
            options={
                'db_table': 'chef_inventory_items',
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='gestion_cocinero.dish')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_dishes', to='gestion_cocinero.inventoryitem')),
            ],
            options={
                'db_table': 'chef_dish_ingredients',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.DecimalField(decimal_places=4, max_digits=12)),
                ('movement_type', models.CharField(max_length=30)),
                ('reference_id', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='gestion_cocinero.inventoryitem')),
            ],
            options={
                'db_table': 'chef_stock_movements',
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['chef', 'name'], name='chef_invent_chef_id_949b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['deleted_at'], name='chef_invent_deleted_89a57b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dishingredient',
            unique_together={('dish', 'inventory_item')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['inventory_item', 'created_at'], name='chef_stock__invento_8cac78_idx'),
        ),
    ]
