# Generated by Django 5.2.14 on 2026-06-17 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cocinero', '0003_chefavailability_deleted_at_chefavailability_version_and_more'),
        ('gestion_usuarios_acceso_suscripcion', '0006_alter_aipaymentmethod_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='admin_review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dishes', to='gestion_usuarios_acceso_suscripcion.userprofile'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ia_quality_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dish',
            name='ia_quality_recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ia_quality_review_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='dish',
            name='ia_risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='last_quality_analysis_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='reported_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='revision_status',
            field=models.CharField(default='pendiente_revision_ia', max_length=40),
        ),
    ]
