# Generated by Django 5.2.14 on 2026-06-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cocinero', '0004_dish_admin_review_comment_dish_admin_reviewed_at_and_more'),
        ('gestion_cocinero', '0004_inventoryitem_dishingredient_stockmovement_and_more'),
    ]

    operations = [
    ]
