# Generated by Django 5.2.14 on 2026-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cocinero', '0005_merge_20260617_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ia_text_risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
