# Generated by Django 5.2.14 on 2026-06-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cocinero', '0005_merge_20260617_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='kitchen_photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
