# Generated by Django 5.2.14 on 2026-06-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cocinero', '0006_chefprofile_kitchen_photos'),
        ('gestion_cocinero', '0006_dish_ia_text_risk_score'),
    ]

    operations = [
    ]
